### ISSUE TITLE
Unexpected Fixture behavior

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube-test-utils#23]
What I expect from the test life cycle:
1) if I catch some exception in `setup` of my Fixture I expect that Fixture's `tearDown` will be invoked. Because only the fixture implementation knows how to release allocated resources.
2) also if I catch some exception in `setup` of my Fixture apart from 1 point we should not run a test (for `Lifecycle.PER_METHOD`) or all tests (for `Lifecycle.PER_CLASS`). Moreover `TestAbortedException` doesn't work.

**Comment by dmytro-lazebnyi** [comment]
Currently, a test is skipped (instead of being failed) if `TestAbortedException` is thrown from `setUp` method.

**Comment by aharonha** [comment]
@dmytro-lazebnyi This is intentionally built like this. It means that there was no issue in the business of the system-under-test but in the integration of it in the real-product (e.g. when you have issues in the database integration - a mock fixture will not fail, while a production-like-environment will 'skip')
