### ISSUE TITLE
Set of fixtures

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube-test-utils#31]
Give an opportunity to specify a set of fixtures for 1 test case, for example:

```java

@Fixtures(value = {
    @Fixture(DatabaseFixture.class),
    @Fixture(HistoryService.class),
    @Fixture(AnotherService.class),
})
```

Also, @Fixtures should be repeatable.
It will rid us lots of the copy-paste code and strange inheritance.

**Comment by segabriel** [comment]
@aharonha WDYT?

**Comment by aharonha** [comment]
`@WithFixture` is repeatable, so use like this:
```
@ExtendWith(Fixtures.class)
@WithFixture(value = FasterServiceFixture.class, lifecycle = Lifecycle.PER_CLASS)
@WithFixture(value = SlowServiceFixture.class, lifecycle = Lifecycle.PER_METHOD)
public class SimpleInMemoryTest extends BaseTest {
```
see `io.scalecube.test.fixtures.SimpleInMemoryTest` in `scalecube-fixtures-tck-flow/src/test/java/io/scalecube/test/fixtures/SimpleInMemoryTest.java`

**Comment by segabriel** [comment]
@aharonha if you look at the exhcange fixture for history service you see that we have an ugly inheritance and have no capability setup some set of fixture for one test.


That example
```
@ExtendWith(Fixtures.class)
@WithFixture(value = FasterServiceFixture.class, lifecycle = Lifecycle.PER_CLASS)
@WithFixture(value = SlowServiceFixture.class, lifecycle = Lifecycle.PER_METHOD)
public class SimpleInMemoryTest extends BaseTest
```
It shows only that we have two different tests (fixture per test) I'd like to have one test and specify different started environments for it. I don't want to define all things in 1 place, I wanted to create a few different fixtures and combinate them for some test. For example, there are database fixture, some service fixture, and Kafka fixture. And for some test, I need to use the only database and service fixtures for another test is needed service and Kafka fixture.

**Comment by aharonha** [comment]
So you want a composition? this is fine. i'm on it. #
Nevertheless this composition should define its connectivity, which must be done in the fixture setup itself.
moreover, fixtures should set teardown and setup sequence of internals, which I will also support.

**Comment by segabriel** [comment]
Yeap it's kinda composition and each such a fixture (history, service and Kafka) should have its life cycle with stop/start methods
