### ISSUE TITLE
Add properties to setup

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube-test-utils#32]
Currently, we can't specify any properties for starting of the fixture. IMHO we can add properties as an argument to `setUp` method. And we can add an ability to set part of these properties via annotations, it will look like the following:

```java
@Fixture(...., properties=["io.scalecube.snapshotBarrier=10", "key=value"])
```

And refactor `void setUp()` to:

```java
void setUp(Properties properties) throws TestAbortedException; // it can be Map<String, String> 
```

Also, the properties should contain:
1) custom properties via annotations (high priority)
2) java properties (`-D`)
3) system properties

**Comment by aharonha** [comment]
@segabriel 2 & 3 are the same, unless you mean environment variables.
Environment variables conventions defer from java conventions, so maybe let's postpone this for now.

**Comment by segabriel** [comment]
@aharonha JUnit tests are run in the same JVM instance and a test shouldn't affect on another test (when props were set via java (-D) and system properties). For example, a value of someCountBarrier can affect two tests. One test expects 3 (has logic for related to this value) and another expects 4. And it will be better to set them via some custom map as mentioned in the description and give access to them.
2nd and 3rd points are really the same but it will easier to have props where custom definitions (which were defined in annotations) will have higher priority than the system props.

**Comment by segabriel** [comment]
Currently, we have two the same fixtures in the exchange which have the difference only in `snapshotCountBarrier`

**Comment by aharonha** [comment]
With the ability to compose fixtures, you can create an interface setting up some values (fixture configuration). Inject it through the constructor, and as you `setUp` use the values as you wish.
Will this be suffice?
